/**
 * Created by wuqiongke on 16/7/24.
 */
var orderList = {
    "code": "0",
    "msg": "Success",
    "data": {
        "orderList": [
            {
                "orderId": 201607230001,
                "orderDate": "2016.06.03",
                "projectId": "1607230001001",
                "projectName": "美团外卖",
                "executeKOL": "追风少年刘全有",
                "type": "直发",
                "sendOut": "否",
                "url": "wwww.weibo.com/23124343",
                "amount": "15000",
                "paid": "3000",
                "customerInfo": "妞妞",
                "customerType": "",
                "paidWay": "楼氏公账",
                "paidName": "背景环宇傲视国际传媒广告有限公司",
                "operator": "柏生",
                "paidTime": "2016.06.03",
                "description": "微任务-框架客户..."
            },
            {
                "orderId": 201607230001,
                "orderDate": "2016.06.03",
                "projectId": "1607230001001",
                "projectName": "美团外卖",
                "executeKOL": "追风少年刘全有",
                "type": "直发",
                "sendOut": "否",
                "url": "wwww.weibo.com/23124343",
                "amount": "15000",
                "paid": "3000",
                "customerInfo": "妞妞",
                "customerType": "",
                "paidWay": "楼氏公账",
                "paidName": "背景环宇傲视国际传媒广告有限公司",
                "operator": "柏生",
                "paidTime": "2016.06.03",
                "description": "微任务-框架客户..."
            },
            {
                "orderId": 201607230001,
                "orderDate": "2016.06.03",
                "projectId": "1607230001001",
                "projectName": "美团外卖",
                "executeKOL": "追风少年刘全有",
                "type": "直发",
                "sendOut": "否",
                "url": "wwww.weibo.com/23124343",
                "amount": "15000",
                "paid": "3000",
                "customerInfo": "妞妞",
                "customerType": "",
                "paidWay": "楼氏公账",
                "paidName": "背景环宇傲视国际传媒广告有限公司",
                "operator": "柏生",
                "paidTime": "2016.06.03",
                "description": "微任务-框架客户..."
            },
            {
                "orderId": 201607230001,
                "orderDate": "2016.06.03",
                "projectId": "1607230001001",
                "projectName": "美团外卖",
                "executeKOL": "追风少年刘全有",
                "type": "直发",
                "sendOut": "否",
                "url": "wwww.weibo.com/23124343",
                "amount": "15000",
                "paid": "3000",
                "customerInfo": "妞妞",
                "customerType": "",
                "paidWay": "楼氏公账",
                "paidName": "背景环宇傲视国际传媒广告有限公司",
                "operator": "柏生",
                "paidTime": "2016.06.03",
                "description": "微任务-框架客户..."
            },
            {
                "orderId": 201607230001,
                "orderDate": "2016.06.03",
                "projectId": "1607230001001",
                "projectName": "美团外卖",
                "executeKOL": "追风少年刘全有",
                "type": "直发",
                "sendOut": "否",
                "url": "wwww.weibo.com/23124343",
                "amount": "15000",
                "paid": "3000",
                "customerInfo": "妞妞",
                "customerType": "",
                "paidWay": "楼氏公账",
                "paidName": "背景环宇傲视国际传媒广告有限公司",
                "operator": "柏生",
                "paidTime": "2016.06.03",
                "description": "微任务-框架客户..."
            },
            {
                "orderId": 201607230001,
                "orderDate": "2016.06.03",
                "projectId": "1607230001001",
                "projectName": "美团外卖",
                "executeKOL": "追风少年刘全有",
                "type": "直发",
                "sendOut": "否",
                "url": "wwww.weibo.com/23124343",
                "amount": "15000",
                "paid": "3000",
                "customerInfo": "妞妞",
                "customerType": "",
                "paidWay": "楼氏公账",
                "paidName": "背景环宇傲视国际传媒广告有限公司",
                "operator": "柏生",
                "paidTime": "2016.06.03",
                "description": "微任务-框架客户..."
            },
            {
                "orderId": 201607230001,
                "orderDate": "2016.06.03",
                "projectId": "1607230001001",
                "projectName": "美团外卖",
                "executeKOL": "追风少年刘全有",
                "type": "直发",
                "sendOut": "否",
                "url": "wwww.weibo.com/23124343",
                "amount": "15000",
                "paid": "3000",
                "customerInfo": "妞妞",
                "customerType": "",
                "paidWay": "楼氏公账",
                "paidName": "背景环宇傲视国际传媒广告有限公司",
                "operator": "柏生",
                "paidTime": "2016.06.03",
                "description": "微任务-框架客户..."
            }
        ]
    }
};